#!/bin/sh

# TODO: Credentials from local environment file.

# This will typically be run once per year or so; whatever the duration of the certificate is.
# Once the CSR is sent, the private key MUST be preserved in a safe, secure location. It will be needed
# in order to load the cert that will be generated by the signing authority onto server instances.

UNIQUE_SUFFIX=`date "+%Y-%m-%dT%H%M"`


openssl req -new\
 -newkey rsa:2048\
 -nodes\
 -out star_example_com.$UNIQUE_SUFFIX.csr\
 -keyout star_example_com.$UNIQUE_SUFFIX.key\
 -subj "/C=US/ST=ExampleState/L=ExampleCity/O=ExampleOrg ./CN=*.example.com"\
